Config = {}

--Relationship Setup
AddRelationshipGroup("SUB_CREW") --creates a new relationship group for submarine crew
SetRelationshipBetweenGroups(5, "SUB_CREW", "PLAYER") --sets submarine crew to hate player peds
SetRelationshipBetweenGroups(0, "SUB_CREW", "SUB_CREW") --sets submarine crew to be companions with each other

AddRelationshipGroup("CANAPA_CREW")
SetRelationshipBetweenGroups(5, "CANAPA_CREW", "PLAYER")
SetRelationshipBetweenGroups(0, "CANAPA_CREW", "CANAPA_CREW")

AddRelationshipGroup("OIL_CREW")
SetRelationshipBetweenGroups(5, "OIL_CREW", "PLAYER")
SetRelationshipBetweenGroups(0, "OIL_CREW", "OIL_CREW")

Config.Peds = {
  
  ---
  --Neutral
  ---
  { model="s_f_y_stripper_02", 
  x= 776.42,y= 1288.32,z= 360.29,a= 91.23,
  anim="mini@strip_club@private_dance@idle", 
  animName="priv_dance_idle",
  stoic=true,
  voice=female,
  soldier=false,
  lightarms=false,
  mediumarms=false,
  heavyarms=false,
  relationship=nil,
	god=false,
	task=nil,
  extrahealth=false},
  ---
  { model="s_f_y_stripper_02", 
  x= 747.07,y= 1279.06,z= 360.29,a= 142.70, 
  anim="mini@strip_club@lap_dance@ld_girl_a_song_a_p1", 
  animName="ld_girl_a_song_a_p1_f",
  stoic=true,
  voice=female,
  soldier=false,
  lightarms=false,
  mediumarms=false,
  heavyarms=false,
  relationship=nil,
	god=false,
	task=nil,
  extrahealth=false},
  --- 
  { model="csb_stripper_01", 
  x= 737.29,y= 1282.28,z= 360.29,a= 70.02,
  anim="mini@strip_club@private_dance@part2", 
  animName="priv_dance_p2",
  stoic=true,
  voice=female,
  soldier=false,
  lightarms=false,
  mediumarms=false,
  heavyarms=false,
  relationship=nil,
	god=false,
	task=nil,
  extrahealth=false},
    ---
    --Hostiles (SUB_CREW)
    ---
  { model="csb_bogdan",
  x= 801.32,y= 1280.76,z= 360.29,a= 266.95,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="csb_bogdan",
  x=800.75,y= 1271.00,z= 360.29,a= 257.52,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  --- 
  { model="csb_bogdan",
  x= 765.9590,y= 1275.1963,z= 360.2966,a= 90.8659,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
    ---
  { model="csb_bogdan",
  x= 759.8297,y= 1280.5812,z= 360.2966,a= 172.5395,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="csb_bogdan",
  x= 741.4689,y= 1312.5049,z= 360.1320,a= 174.6826,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=true,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  --- 
  { model="csb_bogdan",
  x= 720.8813,y= 1291.4758,z= 360.2962,a= 175.8951,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=true,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
    ---
  { model="csb_bogdan",
  x= 660.79,y= 1282.38,z= 360.29,a= 261.73,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=true,
  heavyarms=false,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="mp_m_bogdangoon",
  x= 681.20,y= 1284.72,z= 360.29,a= 306.97,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=false,
  heavyarms=true,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=true},
  --- 
  { model="mp_m_bogdangoon",
  x= 705.76,y= 1284.34,z= 360.29,a= 265.67,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=false,
  heavyarms=true,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=true},
    ---
  { model="mp_m_bogdangoon",
  x= 713.53,y= 1285.70,z= 360.29,a= 156.58,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=false,
  heavyarms=true,
  relationship="SUB_CREW",
  god=false,
  task=nil,
  extrahealth=true},
    ---
    --Hostile 2 (CANAPA)
    ---
  { model="g_m_y_lost_01",
  x= 2196.0620,y= 5595.7754,z= 53.7769,a= 263.3651,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="CANAPA_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="g_m_y_lost_02",
  x= 2191.9316,y= 5601.4297,z= 53.6970,a= 350.6529,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="CANAPA_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="g_m_y_lost_03",
  x= 2219.5706,y= 5578.6006,z= 53.7287,a= 266.7983,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="CANAPA_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="g_m_m_chicold_01",
  x= 2224.3838,y= 5604.5361,z= 54.9226,a= 107.6634,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=false,
  heavyarms=true,
  relationship="CANAPA_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="g_m_m_chigoon_01",
  x= 2221.8066,y= 5614.6406,z= 54.9016,a= 107.9302,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=false,
  heavyarms=true,
  relationship="CANAPA_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  { model="g_m_y_armgoon_02",
  x= 2226.3779,y= 5624.7822,z= 54.4717,a= 168.1340,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=false,
  mediumarms=false,
  heavyarms=true,
  relationship="CANAPA_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
  --Hostile 2 (OIL)
  ---
  { model="cs_old_man1a", --cs_old_man2 cs_omega s_m_m_trucker_01 u_m_y_dancerave_01 u_m_y_hippie_01 u_m_y_mani u_m_y_militarybum
  x=425.0971,y= 2997.2654,z= 40.5233,a= 14.5215,
  anim=nil,
  animName=nil,
  stoic=false,
  voice=male,
  soldier=true,
  lightarms=true,
  mediumarms=false,
  heavyarms=false,
  relationship="OIL_CREW",
  god=false,
  task=nil,
  extrahealth=false},
  ---
}
